name: smart_student_hub
description: Smart Student Hub - Mobile App for Student Achievement Tracking

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Navigation
  go_router: ^12.1.3

  # Forms & Validation
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1

  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.2

  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1

  # Notifications
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.10

  # Authentication
  local_auth: ^2.1.7
  biometric_storage: ^4.1.3

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  permission_handler: ^11.2.0

  # Analytics
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700


